# individual settings for greater control
headings = [
    {
        "name": "ID",
        "column_size": 4 * 1.2,
        "font_name": "Arial",
        "font_size": 12,
        "bold": True,
        "h_align": "right",
        "v_align": "center",
        "text_color": "d90429",
        "bg_color": "dae2e4",
    },
    {
        "name": "URL",
        "column_size": 5 * 1.2,
        "font_name": "Arial",
        "font_size": 12,
        "bold": True,
        "h_align": "center",
        "v_align": "center",
        "text_color": "012a4a",
        "bg_color": "eaeef0",
    },
    {
        "name": "Type",
        "column_size": 6 * 1.2,
        "font_name": "Arial",
        "font_size": 12,
        "bold": True,
        "h_align": "center",
        "v_align": "center",
        "text_color": "9b2226",
        "bg_color": "eaeef0",
    },
    {
        "name": "Created Date",
        "column_size": 14 * 1.2,
        "font_name": "Arial",
        "font_size": 10,
        "bold": True,
        "h_align": "center",
        "v_align": "top",
        "text_color": "343a40",
        "bg_color": "eaeef0",
    },
    {
        "name": "Download Date",
        "column_size": 15 * 1.2,
        "font_name": "Arial",
        "font_size": 14,
        "bold": True,
        "h_align": "center",
        "v_align": "center",
        "text_color": "642957",
        "bg_color": "eaeef0",
    },
]

data = [
    [
        1,
        "https://www.youtube.com/watch\?v\=6c2hT_f5Q2g",
        "video+desc",
        "2021-05-08 14:11:12",
        "",
    ],
    [
        2,
        "https://www.youtube.com/watch?v=WLTymkEVn5s",
        "audio",
        "2021-05-09 14:13:14",
        "",
    ],
    [
        3,
        "https://www.youtube.com/watch?v=sWBxZjnrrbc",
        "audio+desc",
        "2021-05-10 15:15:16",
        "",
    ],
    [
        4,
        "https://www.youtube.com/watch?v=1_mJI426TCo",
        "video",
        "2021-05-11 16:17:18",
        "",
    ],
    [
        5,
        "https://www.youtube.com/watch?v=NBRGZnoOblE",
        "audio",
        "2021-05-11 18:21:22",
        "",
    ],
    [
        6,
        "https://www.youtube.com/watch?v=NFYw7jVkMxI",
        "audio+desc",
        "2021-05-12 21:13:11",
        "",
    ],
    [
        7,
        "https://www.youtube.com/watch?v=hWZuTWAvWrA",
        "video",
        "2021-05-12 09:10:23",
        "",
    ],
    [
        8,
        "https://www.youtube.com/watch?v=KO0OYCbDPRM",
        "audio",
        "2021-05-13 09:20:00",
        "",
    ],
    [
        9,
        "https://www.youtube.com/watch?v=6c2hT_f5Q2g",
        "video+desc",
        "2021-05-13 09:20:00",
        "",
    ],
]